import type { Prior } from "./types";

// The 45 curated physiological relationships (P01–P45), seeded verbatim from
// build/01-priors-knowledge-base.md. This is Helix's credibility moat — it
// keeps Claude anchored to real mechanisms instead of hallucinating.
export const PRIORS: Prior[] = [
  // A. Sleep -> Recovery -> Downstream (Act 1 backbone)
  {
    id: "P01",
    cause: "sleep_consistency",
    effect: "recovery_score",
    type: "reduces",
    mechanism:
      "Irregular sleep timing disrupts circadian rhythm and autonomic recovery, lowering overnight HRV and recovery.",
    evidence_signals: ["sleep_consistency", "hrv", "recovery_score"],
    confidence: 0.85,
    domain: "sleep",
    requires_clinician: false,
  },
  {
    id: "P02",
    cause: "sleep_duration",
    effect: "recovery_score",
    type: "drives",
    mechanism:
      "Insufficient total sleep limits restorative deep and REM sleep needed for physiological recovery.",
    evidence_signals: ["sleep_duration", "deep_sleep", "recovery_score"],
    confidence: 0.8,
    domain: "sleep",
    requires_clinician: false,
  },
  {
    id: "P03",
    cause: "recovery_score",
    effect: "activity_level",
    type: "drives",
    mechanism:
      "Low recovery reduces readiness and training capacity, so daily activity and workout volume fall.",
    evidence_signals: ["recovery_score", "activity_level", "workout_performance"],
    confidence: 0.75,
    domain: "recovery",
    requires_clinician: false,
  },
  {
    id: "P04",
    cause: "recovery_score",
    effect: "afternoon_fatigue",
    type: "reduces",
    mechanism:
      "Poor overnight recovery leaves lower daytime energy reserves, surfacing as afternoon fatigue.",
    evidence_signals: ["recovery_score", "hrv", "afternoon_fatigue"],
    confidence: 0.78,
    domain: "recovery",
    requires_clinician: false,
  },
  {
    id: "P05",
    cause: "sleep_consistency",
    effect: "afternoon_fatigue",
    type: "drives",
    mechanism:
      "Variable sleep/wake timing causes circadian misalignment that manifests as predictable afternoon energy crashes.",
    evidence_signals: ["sleep_consistency", "afternoon_fatigue"],
    confidence: 0.7,
    domain: "sleep",
    requires_clinician: false,
  },
  {
    id: "P06",
    cause: "hrv",
    effect: "recovery_score",
    type: "drives",
    mechanism:
      "Higher heart-rate variability reflects stronger parasympathetic recovery and underlies recovery scoring.",
    evidence_signals: ["hrv", "recovery_score"],
    confidence: 0.82,
    domain: "recovery",
    requires_clinician: false,
  },
  {
    id: "P07",
    cause: "resting_hr",
    effect: "recovery_score",
    type: "reduces",
    mechanism:
      "Elevated resting heart rate signals incomplete recovery or accumulated strain, depressing recovery.",
    evidence_signals: ["resting_hr", "recovery_score"],
    confidence: 0.72,
    domain: "recovery",
    requires_clinician: false,
  },
  {
    id: "P08",
    cause: "sleep_consistency",
    effect: "deep_sleep",
    type: "drives",
    mechanism: "Stable sleep timing increases the proportion of restorative deep sleep.",
    evidence_signals: ["sleep_consistency", "deep_sleep"],
    confidence: 0.68,
    domain: "sleep",
    requires_clinician: false,
  },

  // B. Activity / Training -> Outcomes
  {
    id: "P09",
    cause: "activity_level",
    effect: "weight_trend",
    type: "drives",
    mechanism:
      "Reduced activity lowers total energy expenditure, contributing to weight-loss plateaus.",
    evidence_signals: ["activity_level", "weight_trend", "calorie_intake"],
    confidence: 0.7,
    domain: "activity",
    requires_clinician: false,
  },
  {
    id: "P10",
    cause: "recovery_score",
    effect: "workout_performance",
    type: "drives",
    mechanism:
      "Training on low recovery limits output, so workout quality and progression decline.",
    evidence_signals: ["recovery_score", "workout_performance"],
    confidence: 0.76,
    domain: "activity",
    requires_clinician: false,
  },
  {
    id: "P11",
    cause: "activity_level",
    effect: "recovery_score",
    type: "increases",
    mechanism:
      "Appropriate aerobic activity improves cardiovascular fitness and baseline HRV over time (U-shaped — excess strain reverses this).",
    evidence_signals: ["activity_level", "recovery_score", "hrv"],
    confidence: 0.6,
    domain: "activity",
    requires_clinician: false,
  },
  {
    id: "P12",
    cause: "workout_performance",
    effect: "weight_trend",
    type: "drives",
    mechanism:
      "Declining workout output reduces caloric burn and lean-mass stimulus, slowing fat loss.",
    evidence_signals: ["workout_performance", "weight_trend"],
    confidence: 0.55,
    domain: "activity",
    requires_clinician: false,
  },

  // C. Nutrition -> Recovery / Body Composition
  {
    id: "P13",
    cause: "protein_intake",
    effect: "recovery_score",
    type: "drives",
    mechanism:
      "Adequate protein supplies amino acids for muscle repair; low intake impairs recovery and adaptation.",
    evidence_signals: ["protein_intake", "recovery_score", "workout_performance"],
    confidence: 0.72,
    domain: "nutrition",
    requires_clinician: false,
  },
  {
    id: "P14",
    cause: "calorie_intake",
    effect: "weight_trend",
    type: "drives",
    mechanism:
      "Sustained energy deficit drives weight loss; a closing deficit produces a plateau.",
    evidence_signals: ["calorie_intake", "weight_trend", "activity_level"],
    confidence: 0.8,
    domain: "nutrition",
    requires_clinician: false,
  },
  {
    id: "P15",
    cause: "protein_intake",
    effect: "workout_performance",
    type: "drives",
    mechanism:
      "Insufficient protein limits muscle repair and strength expression, degrading workout performance.",
    evidence_signals: ["protein_intake", "workout_performance"],
    confidence: 0.62,
    domain: "nutrition",
    requires_clinician: false,
  },
  {
    id: "P16",
    cause: "calorie_intake",
    effect: "afternoon_fatigue",
    type: "drives",
    mechanism:
      "Very low energy intake or skipped meals can reduce available glucose, contributing to afternoon fatigue.",
    evidence_signals: ["calorie_intake", "afternoon_fatigue"],
    confidence: 0.55,
    domain: "nutrition",
    requires_clinician: false,
  },
  {
    id: "P17",
    cause: "hydration",
    effect: "afternoon_fatigue",
    type: "drives",
    mechanism: "Mild dehydration reduces alertness and contributes to perceived fatigue.",
    evidence_signals: ["hydration", "afternoon_fatigue"],
    confidence: 0.45,
    domain: "nutrition",
    requires_clinician: false,
  },

  // D. Biomarkers -> Energy / Recovery (Act 2 backbone)
  {
    id: "P18",
    cause: "ferritin",
    effect: "energy_level",
    type: "drives",
    mechanism:
      "Low ferritin (iron stores) limits oxygen transport and cellular energy production, reducing energy.",
    evidence_signals: ["ferritin", "energy_level", "afternoon_fatigue"],
    confidence: 0.82,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P19",
    cause: "energy_level",
    effect: "exercise_capacity",
    type: "drives",
    mechanism: "Reduced systemic energy lowers tolerance for and output during exercise.",
    evidence_signals: ["energy_level", "exercise_capacity", "workout_performance"],
    confidence: 0.75,
    domain: "biomarker",
    requires_clinician: false,
  },
  {
    id: "P20",
    cause: "exercise_capacity",
    effect: "recovery_score",
    type: "drives",
    mechanism:
      "Diminished exercise capacity strains the body at lower workloads, slowing recovery.",
    evidence_signals: ["exercise_capacity", "recovery_score"],
    confidence: 0.65,
    domain: "biomarker",
    requires_clinician: false,
  },
  {
    id: "P21",
    cause: "ferritin",
    effect: "recovery_score",
    type: "drives",
    mechanism: "Low iron stores impair oxygen delivery and recovery from training load.",
    evidence_signals: ["ferritin", "recovery_score"],
    confidence: 0.7,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P22",
    cause: "vitamin_d",
    effect: "energy_level",
    type: "drives",
    mechanism:
      "Vitamin D insufficiency is associated with fatigue and reduced muscle function.",
    evidence_signals: ["vitamin_d", "energy_level"],
    confidence: 0.55,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P23",
    cause: "tsh",
    effect: "energy_level",
    type: "drives",
    mechanism:
      "Elevated TSH (underactive thyroid) slows metabolism and commonly causes fatigue and weight changes.",
    evidence_signals: ["tsh", "energy_level", "weight_trend"],
    confidence: 0.7,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P24",
    cause: "hs_crp",
    effect: "recovery_score",
    type: "drives",
    mechanism:
      "Elevated inflammation (hs-CRP) impairs tissue recovery and elevates perceived fatigue.",
    evidence_signals: ["hs_crp", "recovery_score", "afternoon_fatigue"],
    confidence: 0.6,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P25",
    cause: "fasting_glucose",
    effect: "afternoon_fatigue",
    type: "drives",
    mechanism:
      "Dysregulated glucose produces post-prandial crashes experienced as afternoon fatigue.",
    evidence_signals: ["fasting_glucose", "afternoon_fatigue"],
    confidence: 0.55,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P26",
    cause: "testosterone",
    effect: "recovery_score",
    type: "drives",
    mechanism: "Low testosterone reduces muscle recovery, drive, and energy.",
    evidence_signals: ["testosterone", "recovery_score", "energy_level"],
    confidence: 0.55,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P27",
    cause: "vitamin_b12",
    effect: "energy_level",
    type: "drives",
    mechanism:
      "B12 deficiency impairs red blood cell formation and energy metabolism, causing fatigue.",
    evidence_signals: ["vitamin_b12", "energy_level"],
    confidence: 0.55,
    domain: "biomarker",
    requires_clinician: true,
  },
  {
    id: "P28",
    cause: "magnesium",
    effect: "sleep_quality",
    type: "drives",
    mechanism:
      "Low magnesium is associated with poorer sleep quality and more night waking.",
    evidence_signals: ["magnesium", "sleep_quality"],
    confidence: 0.45,
    domain: "biomarker",
    requires_clinician: true,
  },

  // E. Interventions -> Cascades (Act 3 backbone)
  {
    id: "P29",
    cause: "glp1",
    effect: "appetite",
    type: "reduces",
    mechanism:
      "GLP-1 receptor agonists slow gastric emptying and increase satiety, sharply reducing appetite.",
    evidence_signals: ["glp1", "appetite", "calorie_intake"],
    confidence: 0.9,
    domain: "intervention",
    requires_clinician: true,
  },
  {
    id: "P30",
    cause: "appetite",
    effect: "protein_intake",
    type: "drives",
    mechanism:
      "Reduced appetite disproportionately lowers protein intake, which is satiating and harder to consume in deficit.",
    evidence_signals: ["appetite", "protein_intake", "calorie_intake"],
    confidence: 0.7,
    domain: "intervention",
    requires_clinician: false,
  },
  {
    id: "P31",
    cause: "glp1",
    effect: "calorie_intake",
    type: "reduces",
    mechanism:
      "Appetite suppression lowers overall energy intake, the intended effect that also risks under-fueling.",
    evidence_signals: ["glp1", "calorie_intake", "weight_trend"],
    confidence: 0.85,
    domain: "intervention",
    requires_clinician: true,
  },
  {
    id: "P32",
    cause: "glp1",
    effect: "weight_trend",
    type: "drives",
    mechanism: "Reduced energy intake produces weight loss — the therapeutic goal.",
    evidence_signals: ["glp1", "weight_trend", "calorie_intake"],
    confidence: 0.85,
    domain: "intervention",
    requires_clinician: true,
  },
  {
    id: "P33",
    cause: "magnesium_supplement",
    effect: "sleep_quality",
    type: "increases",
    mechanism:
      "Evening magnesium supplementation can improve sleep quality in deficient individuals.",
    evidence_signals: ["magnesium_supplement", "sleep_quality"],
    confidence: 0.4,
    domain: "intervention",
    requires_clinician: false,
  },
  {
    id: "P34",
    cause: "iron_supplement",
    effect: "ferritin",
    type: "increases",
    mechanism:
      "Oral iron supplementation raises ferritin/iron stores over weeks to months.",
    evidence_signals: ["iron_supplement", "ferritin", "energy_level"],
    confidence: 0.7,
    domain: "intervention",
    requires_clinician: true,
  },
  {
    id: "P35",
    cause: "caffeine_late",
    effect: "sleep_quality",
    type: "reduces",
    mechanism:
      "Caffeine consumed late blocks adenosine and delays/lightens sleep, reducing quality.",
    evidence_signals: ["caffeine_late", "sleep_quality", "deep_sleep"],
    confidence: 0.6,
    domain: "intervention",
    requires_clinician: false,
  },
  {
    id: "P36",
    cause: "alcohol",
    effect: "recovery_score",
    type: "reduces",
    mechanism:
      "Alcohol suppresses HRV and disrupts sleep architecture, lowering overnight recovery.",
    evidence_signals: ["alcohol", "recovery_score", "hrv", "deep_sleep"],
    confidence: 0.7,
    domain: "intervention",
    requires_clinician: false,
  },
  {
    id: "P37",
    cause: "creatine",
    effect: "workout_performance",
    type: "increases",
    mechanism: "Creatine supplementation improves strength and high-intensity output.",
    evidence_signals: ["creatine", "workout_performance"],
    confidence: 0.5,
    domain: "intervention",
    requires_clinician: false,
  },

  // F. Cycle (additive modifier)
  {
    id: "P38",
    cause: "luteal_phase",
    effect: "sleep_quality",
    type: "modulates",
    mechanism:
      "The late luteal phase raises core temperature and progesterone shifts, commonly reducing sleep quality.",
    evidence_signals: ["cycle_phase", "sleep_quality", "deep_sleep"],
    confidence: 0.6,
    domain: "cycle",
    requires_clinician: false,
  },
  {
    id: "P39",
    cause: "luteal_phase",
    effect: "recovery_score",
    type: "reduces",
    mechanism:
      "Hormonal shifts in the late luteal phase elevate resting HR and lower HRV, reducing recovery.",
    evidence_signals: ["cycle_phase", "recovery_score", "resting_hr", "hrv"],
    confidence: 0.55,
    domain: "cycle",
    requires_clinician: false,
  },
  {
    id: "P40",
    cause: "luteal_phase",
    effect: "cravings",
    type: "increases",
    mechanism:
      "Late-luteal hormonal changes increase appetite and carbohydrate cravings.",
    evidence_signals: ["cycle_phase", "cravings", "calorie_intake"],
    confidence: 0.55,
    domain: "cycle",
    requires_clinician: false,
  },
  {
    id: "P41",
    cause: "luteal_phase",
    effect: "afternoon_fatigue",
    type: "drives",
    mechanism:
      "Reduced sleep quality and recovery in the late luteal phase surface as increased daytime fatigue.",
    evidence_signals: ["cycle_phase", "afternoon_fatigue", "recovery_score"],
    confidence: 0.5,
    domain: "cycle",
    requires_clinician: false,
  },

  // G. Symptom / Mood cross-links
  {
    id: "P42",
    cause: "recovery_score",
    effect: "mood",
    type: "drives",
    mechanism:
      "Chronic low recovery and poor sleep degrade mood and emotional regulation.",
    evidence_signals: ["recovery_score", "mood", "sleep_quality"],
    confidence: 0.6,
    domain: "symptom",
    requires_clinician: false,
  },
  {
    id: "P43",
    cause: "afternoon_fatigue",
    effect: "cravings",
    type: "drives",
    mechanism: "Energy dips drive compensatory cravings for quick-energy foods.",
    evidence_signals: ["afternoon_fatigue", "cravings"],
    confidence: 0.5,
    domain: "symptom",
    requires_clinician: false,
  },
  {
    id: "P44",
    cause: "sleep_quality",
    effect: "brain_fog",
    type: "drives",
    mechanism: "Poor sleep quality impairs next-day cognitive clarity and focus.",
    evidence_signals: ["sleep_quality", "brain_fog", "deep_sleep"],
    confidence: 0.65,
    domain: "symptom",
    requires_clinician: false,
  },
  {
    id: "P45",
    cause: "protein_intake",
    effect: "cravings",
    type: "reduces",
    mechanism:
      "Higher protein increases satiety and stabilizes appetite, reducing cravings.",
    evidence_signals: ["protein_intake", "cravings"],
    confidence: 0.5,
    domain: "nutrition",
    requires_clinician: false,
  },
];

// Compact JSON form injected into the cached system prompt.
export function priorsForPrompt() {
  return PRIORS.map((p) => ({
    id: p.id,
    cause: p.cause,
    effect: p.effect,
    type: p.type,
    mechanism: p.mechanism,
    confidence: p.confidence,
    requires_clinician: p.requires_clinician,
  }));
}
